### ISSUE TITLE
import m2salesforce.sql แล้วเจอ error ครับ

### ISSUE THREAD

**Issue by kpping** [juthakiat/m1services#1]
Preparing...
Importing m2salesforce.sql...
Finished executing script
**ERROR 1292 (22007) at line 586: Incorrect datetime value: '0000-00-00 00:00:00' for column 'modified_dt' at row 2**
Operation failed with exitcode 1

ไม่รู้ว่าจะมีผลตอน test หรือเปล่าครับ

**Comment by madoatz** [comment]
Line 586 เป็น Insert ข้อมูลจังหวัดเข้า Table type_locale_province ครับ. กำหนดเป็น timestamp ไว้ครับ 
น่าจะ Insert ข้อมูลไม่สมบูรณ์ครับ แต่ยังไม่ใช้ตอนนี้ครับ  ไว้รอ Dumpfile รอบหน้าได้ครับ เดี๋ยวเช็คให้ครับ 

![timestamp](https://cloud.githubusercontent.com/assets/11155438/12973809/deab9078-d0e1-11e5-8dde-12a5ef3d410c.png)
